// <auto-generated />
using System;
using LifeV2.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LifeV2.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250101000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LifeV2.Domain.Entities.Beneficiary", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
                    b.Property<string>("FullName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<Guid>("PolicyId").HasColumnType("uniqueidentifier");
                    b.Property<string>("Relationship").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<decimal>("SharePercentage").HasColumnType("decimal(5,2)");
                    b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("PolicyId");
                    b.ToTable("Beneficiaries", (string)null);
                });

            modelBuilder.Entity("LifeV2.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<decimal>("CoverageAmount").HasColumnType("decimal(18,2)");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
                    b.Property<DateTime?>("EndDate").HasColumnType("datetime2");
                    b.Property<decimal>("MonthlyPremium").HasColumnType("decimal(18,2)");
                    b.Property<string>("PolicyNumber").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<Guid>("PolicyholderId").HasColumnType("uniqueidentifier");
                    b.Property<string>("ProductName").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<DateTime>("StartDate").HasColumnType("datetime2");
                    b.Property<int>("Status").HasColumnType("int");
                    b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("PolicyholderId");
                    b.HasIndex("PolicyNumber").IsUnique();
                    b.ToTable("Policies", (string)null);
                });

            modelBuilder.Entity("LifeV2.Domain.Entities.Policyholder", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
                    b.Property<DateTime>("DateOfBirth").HasColumnType("datetime2");
                    b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<DateTime?>("UpdatedAtUtc").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("Policyholders", (string)null);
                });

            modelBuilder.Entity("LifeV2.Domain.Entities.Beneficiary", b =>
                {
                    b.HasOne("LifeV2.Domain.Entities.Policy", "Policy")
                        .WithMany("Beneficiaries")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Policy");
                });

            modelBuilder.Entity("LifeV2.Domain.Entities.Policy", b =>
                {
                    b.HasOne("LifeV2.Domain.Entities.Policyholder", "Policyholder")
                        .WithMany("Policies")
                        .HasForeignKey("PolicyholderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("Policyholder");
                });

            modelBuilder.Entity("LifeV2.Domain.Entities.Policy", b =>
                {
                    b.Navigation("Beneficiaries");
                });

            modelBuilder.Entity("LifeV2.Domain.Entities.Policyholder", b =>
                {
                    b.Navigation("Policies");
                });
#pragma warning restore 612, 618
        }
    }
}
